-- Execute uma vez no SQL Editor do projeto Supabase antes de publicar o backend.
CREATE TABLE IF NOT EXISTS public.convites_usuario (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(320) NOT NULL,
  token_hash varchar(64) NOT NULL,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_convites_usuario_token_hash UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_convites_usuario_email
  ON public.convites_usuario (email);

CREATE INDEX IF NOT EXISTS idx_convites_usuario_expiracao
  ON public.convites_usuario (expires_at)
  WHERE accepted_at IS NULL;
